import other1 from "../components/images/other-1.png";
import other2 from "../components/images/other-2.png";
import scandic from "../components/images/scandic.png";
import userImg from "../components/images/other-2.png"

export const videoData = [
  {
    id: 1,
    title: "Content writing for Stockholm",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other1,
    userImg,
    videoId: "yawXq5TlgBU",
    play: false,
  },
  {
    id: 2,
    title: "Content writing for Malmo",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other2,
    userImg,
    videoId: "X-feiUdp5Qw",
    play: false,
  },
  {
    id: 3,
    title: "Content writing for Oslo",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: scandic,
    userImg,
    videoId: "MQSRSfnUtTo",
    play: false,
  },
  {
    id: 4,
    title: "Content writing for Stockholm",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other1,
    userImg,
    videoId: "R1PxV3DgTdE",
    play: false,
  },

  {
    id: 5,
    title: "Content writing for Malmo",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other2,
    userImg,
    videoId: "XCctQqXj248",
    play: false,
  },

  {
    id: 6,
    title: "Content writing for Oslo",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: scandic,
    userImg,
    videoId: "nC5A7IK7ws8",
    play: false,
  },

  {
    id: 7,
    title: "Content writing for Stockholm",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other2,
    userImg,
    videoId: "wKyYwgE8Kjg",
    play: false,
  },

  {
    id: 8,
    title: "Stockholm design district",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: scandic,
    userImg,
    videoId: "paul4VqkAfU",
    play: false,
  },

  {
    id: 9,
    title: "Content writing for Stockholm",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other1,
    userImg,
    videoId: "nC5A7IK7ws8",
    play: false,
  },

  {
    id: 10,
    title: "Helsinki design district Stockholm",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other2,
    userImg,
    videoId: "wKyYwgE8Kjg",
    play: false,
  },

  {
    id: 11,
    title: "Paris design district",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: scandic,
    userImg,
    videoId: "paul4VqkAfU",
    play: false,
  },

  {
    id: 12,
    title: "Stockholm's design district",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other1,
    userImg,
    videoId: "nC5A7IK7ws8",
    play: false,
  },
  {
    id: 13,
    title: "Helsinki design district",
    name: "sofia",
    likes: 15000,
    liked: false,
    imgPath: other1,
    userImg,
    videoId: "nC5A7IK7ws8",
    play: false,
  },
  // {
  //   id: 14,
  //   title: "Helsinki design district",
  //   name: "sofia",
  //   likes: 15000,
  //   liked: false,
  //   imgPath: other1,
  //   userImg,
  //   videoId: "nC5A7IK7ws8",
  // },
  // {
  //   id: 15,
  //   title: "Stockholm design district",
  //   name: "sofia",
  //   likes: 15000,
  //   liked: false,
  //   imgPath: other1,
  //   userImg,
  //   videoId: "nC5A7IK7ws8",
  // },
  // {
  //   id: 16,
  //   title: "Helsinki design district",
  //   name: "sofia",
  //   likes: 15000,
  //   liked: false,
  //   imgPath: other1,
  //   userImg,
  //   videoId: "nC5A7IK7ws8",
  // },
  // {
  //   id: 17,
  //   title: "Helsinki design district",
  //   name: "sofia",
  //   likes: 15000,
  //   liked: false,
  //   imgPath: other1,
  //   userImg,
  //   videoId: "nC5A7IK7ws8",
  // },
  // {
  //   id: 18,
  //   title: "Paris design district",
  //   name: "sofia",
  //   likes: 15000,
  //   liked: false,
  //   imgPath: other1,
  //   userImg,
  //   videoId: "nC5A7IK7ws8",
  // },
  // {
  //   id: 19,
  //   title: "Stockholm design district",
  //   name: "sofia",
  //   likes: 15000,
  //   liked: false,
  //   imgPath: other1,
  //   userImg,
  //   videoId: "nC5A7IK7ws8",
  // },
];
